# Generated by Django 2.2.15 on 2020-08-12 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question Itself', 'verbose_name_plural': 'List of Questions'},
        ),
    ]
