# Generated by Django 2.2.15 on 2020-08-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200811_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
